FROM debian:stable-slim

RUN apt-get update && \
    apt-get install -y pdns-server pdns-backend-mysql mariadb-client && \
    rm -rf /var/lib/apt/lists/*

COPY pdns.pdns.conf /etc/powerdns/pdns.conf

EXPOSE 53/tcp 53/udp 8081

CMD ["pdns_server", "--daemon=no"]